#!/bin/sh

set -e

# homebrewのインストールがまだであれば、インストールする。
if [ ! -f /opt/homebrew/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# ローカルにドットファイルがなければcloneする。
if [ ! -d ~/dotfiles ]; then
    cd ~
    git clone https://github.com/Damiroquai12/dotfiles.git
fi

# ファイルから一括インストール
brew bundle -v --file=~/dotfiles/Brewfile

# config がなければ作成する。
if [ ! -d ~/.config ]; then
    mkdir ~/.config
fi

# パッケージのリンク
stow -v -d ~/dotfiles/packages -t ~ zsh starship